### ISSUE TITLE
How to add a template for the 404 page

### ISSUE THREAD

**Issue by eugelogic** [eugelogic/matilda#26]
I added a full html document to the template folder, then I tried with a partial one in the content one but had not luck either way.

**Comment by crgeary** [comment]
Create `/content/404.html`.

Then, to test how it looks visit `/404.html` in your browser.

In order to show the 404 template whenever you hit a missing page, it requires server side setup. I suppose I could add support to the `npm run server` command to return this back if you have one.

For now, if you want to test it, you can just visit `/404.html` in your browser to see it. I'll update it :)
